name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    environment: release-test
    steps:
      - name: Release
        run: yarn deploy
